Fix cli_init declaration when -Werror=strict-prototypes is used
The following error appears if the file libcli.h is included in a source
file compiled with strict-prototypes:

libcli/libcli.h:189:8: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  189 | struct cli_def *cli_init();

Setting void as parameter solves the issue.